name: 'Use S3cmd'
description: 'Use S3cmd cli to interact with s3 object storage.'
branding:
  icon: 'award'  
  color: 'green'

inputs:
  region:
    description: 's3 region'
    required: true
  access_key: 
    description: 's3 access key'
    required: true
  secret_key: 
    description: 's3 secret key'
    required: true
  access_token: 
    description: 's3 access token '
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'