on:
  push:
    branches:
      - main

jobs:
  use_s3cmd:
    runs-on: ubuntu-latest
    
    name: Use S3cmd
    steps:
      - name: Set up S3cmd cli tool
        uses: s3-actions/s3cmd@main
        with:
          region: 'eu-central-1'
          access_key: ${{ secrets.S3_ACCESS_KEY }}
          secret_key: ${{ secrets.S3_SECRET_KEY }}

      - name: Interact with object storage
        run: |
          echo 'foo' >> bar
          s3cmd put bar s3://foobarbaz
          buck=$(< /dev/urandom tr -cd "a-g0-9" | head -c 32; echo)
          s3cmd mb s3://$buck
          mkdir -p baz/bar
          echo 'fizz' >> baz/bar/faz
          s3cmd sync --recursive --acl-public s3://$buck
          s3cmd rm -r --force s3://$buck
          s3cmd rb s3://$buck
